FROM nginx:1.27.1-alpine-slim
LABEL MAINTAINER davralin
LABEL org.opencontainers.image.source https://github.com/davralin/containers

ADD index.html /usr/share/nginx/html/
ADD go-away.jpg /usr/share/nginx/html/
