FROM debian:stable-20260223-slim
LABEL MAINTAINER=davralin
LABEL org.opencontainers.image.source=https://github.com/davralin/containers

RUN \
  /usr/bin/apt-get -y update && \
  /usr/bin/apt-get -y install --no-install-recommends \
    ffmpeg \
    streamripper && \
  /usr/bin/rm -rf /var/lib/apt/lists/*